config/routes.rb
Rails.application.routes.draw do

  get ':classroom_name/calendar', to: 'calendar#show'

  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'devise/registrations#new'
    delete '/logout', to: 'devise/sessions#destroy'
  end

  # namespace :api do
  #   api_version(module: 'v1', path: {value: 'v1'}) do
  #     resources :buildings
  #     resources :classrooms
  #     resources :reservations
  #     resources :users
  #     post '/search', to: 'search#index'
  #   end
  # end

  # match '/calendar' => 'class_scheduler#index', format: false, via: [:get, :post]

  root to: 'calendar#show'
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_filter :authenticate_user!

  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @reservations = get_reservations
  end

  private

  def find_classroom
    Classroom.find_by_name(params[:classroom_name]?
      params[:classroom_name].gsub('_', ' '):'')
  end

  def get_reservations
    classroom = find_classroom
    classroom.reservations.try(:start_this_month, @date) if classroom
  end
end

app/views/calendar/show.html.haml
.row
  -#.col-md-12.text-center
  -#  .well.controls
  -#    = link_to calendar_path(date: @date - 1.month), class: 'btn btn-default' do
  -#      %i.glyphicon.glyphicon-backward
  -#    = "#{@date.strftime('%B')} #{@date.year}"
  -#    = link_to calendar_path(date: @date + 1.month), class: 'btn btn-default' do
  -#      %i.glyphicon-backward.glyphicon-forward
.row
  .col-md-12
    = calendar @date do |date|
      .day
        = date.day
      .reservations
        - if @reservations
          - reservations_today(date).each do |reservation|
            .reservation{ id: "reservation_#{reservation.id}" }
              = reservation.name
              = format_time reservation.start_time
              \-
              = format_time reservation.end_time